"use client";

import React from "react";
import { Sparkles, Brain, Leaf, AlertTriangle, ArrowRightLeft, TrendingUp, CheckCircle2, ChevronRight, Zap } from "lucide-react";
import { formatINR } from "@/lib/utils";

// Mock Data
const MOCK_METRICS = {
  potentialSavings: 12450,
  urgentActions: 8,
  aiConfidence: "94%",
  itemsProcessed: 4230
};

const MOCK_PRIORITIES = [
  { id: 1, type: "Sell First", item: "Organic Milk 1L", reason: "Expires in 2 days. 45 units remaining.", impact: 2800, color: "red", icon: AlertTriangle },
  { id: 2, type: "Transfer", item: "Avocados (Hass)", reason: "Oversupplied here. HSR Layout store out of stock.", impact: 1500, color: "blue", icon: ArrowRightLeft },
  { id: 3, type: "Discount", item: "Whole Wheat Bread", reason: "Historical slow sales on Tuesdays. Suggest 15% off.", impact: 850, color: "orange", icon: TrendingUp },
  { id: 4, type: "Sell First", item: "Greek Yogurt", reason: "Expires in 3 days. High volume.", impact: 1200, color: "red", icon: AlertTriangle },
];

const MOCK_INSIGHTS = [
  { title: "Weekend Surge Predicted", detail: "Weather forecast indicates rain. Expect 20% higher footfall for comfort foods and bakery items." },
  { title: "Supplier Reliability", detail: "FreshFarm supplier delivery time has improved by 1.5 hours on average this week." },
  { title: "Waste Reduction", detail: "New dynamic pricing strategy reduced dairy waste by 18% compared to last month." }
];

export default function BriefingPage() {
  return (
    <div className="space-y-6 pb-12">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-900 flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-green-600" /> AI Daily Briefing
          </h2>
          <p className="text-sm text-slate-500">Your personalized morning digest generated by GreenShop AI.</p>
        </div>
        <div className="text-xs font-semibold bg-green-100 text-green-700 px-3 py-1.5 rounded-full flex items-center gap-1.5">
          <CheckCircle2 className="w-4 h-4" /> Generated at 07:00 AM
        </div>
      </div>

      {/* Top Banner */}
      <div className="bg-[#063120] rounded-2xl p-6 border border-[#0A412A] text-white relative overflow-hidden flex flex-col md:flex-row justify-between items-center gap-6">
        <div className="absolute top-0 right-0 w-64 h-64 bg-[#0FA958] rounded-full blur-3xl opacity-20 transform translate-x-1/2 -translate-y-1/2" />
        
        <div className="relative z-10 max-w-xl">
          <div className="flex items-center gap-2 mb-2">
            <div className="w-8 h-8 bg-[#0FA958] rounded-full flex items-center justify-center">
              <Brain className="w-4 h-4 text-white" />
            </div>
            <h3 className="font-bold text-lg">Good Morning, Arjun!</h3>
          </div>
          <p className="text-sm text-slate-300 leading-relaxed">
            The AI engine has analyzed your inventory overnight. We've identified <span className="font-bold text-white">{MOCK_METRICS.urgentActions} urgent actions</span> today that could prevent up to <span className="font-bold text-white">{formatINR(MOCK_METRICS.potentialSavings)}</span> in potential waste.
          </p>
        </div>
        
        <div className="relative z-10 flex gap-4 w-full md:w-auto">
          <div className="bg-white/10 border border-white/10 rounded-xl p-4 flex-1 text-center backdrop-blur-sm">
            <div className="text-xs text-slate-300 mb-1">Items Scanned</div>
            <div className="text-xl font-bold">{MOCK_METRICS.itemsProcessed.toLocaleString()}</div>
          </div>
          <div className="bg-white/10 border border-white/10 rounded-xl p-4 flex-1 text-center backdrop-blur-sm">
            <div className="text-xs text-slate-300 mb-1">AI Confidence</div>
            <div className="text-xl font-bold text-green-400">{MOCK_METRICS.aiConfidence}</div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left Column: Priority Actions */}
        <div className="lg:col-span-2 space-y-6">
          <div className="glass-panel p-5">
            <div className="flex justify-between items-center mb-5">
              <h3 className="text-base font-bold text-slate-800 flex items-center gap-2">
                <Zap className="w-4 h-4 text-amber-500" /> Action Items
              </h3>
              <button className="text-xs font-semibold text-blue-600 hover:underline">Accept All</button>
            </div>
            
            <div className="space-y-4">
              {MOCK_PRIORITIES.map((priority) => (
                <div key={priority.id} className={`border border-slate-100 rounded-xl p-4 hover:border-${priority.color}-200 transition-colors flex flex-col sm:flex-row sm:items-center justify-between gap-4`}>
                  <div className="flex items-start gap-3">
                    <div className={`w-10 h-10 rounded-full flex items-center justify-center shrink-0 bg-${priority.color}-50 text-${priority.color}-500`}>
                      <priority.icon className="w-5 h-5" />
                    </div>
                    <div>
                      <div className="flex items-center gap-2 mb-0.5">
                        <span className={`text-[10px] font-bold uppercase tracking-wider text-${priority.color}-600 bg-${priority.color}-50 px-2 py-0.5 rounded`}>
                          {priority.type}
                        </span>
                        <span className="text-xs font-bold text-slate-800">Est. Impact: {formatINR(priority.impact)}</span>
                      </div>
                      <h4 className="text-sm font-bold text-slate-900">{priority.item}</h4>
                      <p className="text-xs text-slate-500 mt-1">{priority.reason}</p>
                    </div>
                  </div>
                  
                  <div className="flex gap-2 sm:shrink-0 w-full sm:w-auto">
                    <button className="flex-1 sm:flex-none text-xs font-bold text-slate-600 bg-slate-100 hover:bg-slate-200 px-4 py-2 rounded-lg transition-colors">
                      Dismiss
                    </button>
                    <button className={`flex-1 sm:flex-none text-xs font-bold text-white bg-${priority.color}-500 hover:bg-${priority.color}-600 px-4 py-2 rounded-lg transition-colors`}>
                      Execute
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right Column: Insights & Trends */}
        <div className="col-span-1 space-y-6">
          <div className="glass-panel p-5">
            <h3 className="text-sm font-bold text-slate-800 mb-4 flex items-center gap-2">
              <Leaf className="w-4 h-4 text-green-600" /> Strategic Insights
            </h3>
            
            <div className="space-y-4">
              {MOCK_INSIGHTS.map((insight, i) => (
                <div key={i} className="bg-slate-50 border border-slate-100 rounded-xl p-4">
                  <h4 className="text-xs font-bold text-slate-900 mb-1">{insight.title}</h4>
                  <p className="text-[11px] text-slate-600 leading-relaxed">{insight.detail}</p>
                </div>
              ))}
            </div>
            
            <button className="w-full mt-4 py-2.5 border border-slate-200 text-slate-600 rounded-lg text-xs font-bold hover:bg-slate-50 transition-colors flex items-center justify-center gap-2">
              Generate Deep Dive Report <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
