import os

with open('lib/api.ts', 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_lines = lines[:1153]
new_lines.append('    ],\n')
new_lines.append('    () => []\n')
new_lines.append('  );\n')
new_lines.append('}\n\n')

new_lines.append('export interface MonthlyReportSummary {\n')
new_lines.append('  month_name: string;\n')
new_lines.append('  total_sales: number;\n')
new_lines.append('  total_transactions: number;\n')
new_lines.append('  waste_prevented_value: number;\n')
new_lines.append('  actual_waste_value: number;\n')
new_lines.append('  avg_green_score: number;\n')
new_lines.append('  top_category: string;\n')
new_lines.append('  top_selling_product: string;\n')
new_lines.append('  generated_at: string;\n')
new_lines.append('}\n\n')

new_lines.append('export async function getMonthlyReport(monthYear?: string): Promise<MonthlyReportSummary> {\n')
new_lines.append('  const q = monthYear ? `?month=${monthYear}` : "";\n')
new_lines.append('  return liveOr(\n')
new_lines.append('    () => apiFetch<MonthlyReportSummary>(`/api/analytics/monthly-report${q}`),\n')
new_lines.append('    () => {\n')
new_lines.append('      const now = new Date();\n')
new_lines.append('      return {\n')
new_lines.append('        month_name: now.toLocaleDateString("en-US", { month: "long", year: "numeric" }),\n')
new_lines.append('        total_sales: 145800.00,\n')
new_lines.append('        total_transactions: 342,\n')
new_lines.append('        waste_prevented_value: 18450.00,\n')
new_lines.append('        actual_waste_value: 1200.00,\n')
new_lines.append('        avg_green_score: 87.5,\n')
new_lines.append('        top_category: "Dairy & Milk",\n')
new_lines.append('        top_selling_product: "Amul Taaza Toned Milk 1L",\n')
new_lines.append('        generated_at: new Date().toISOString()\n')
new_lines.append('      };\n')
new_lines.append('    }\n')
new_lines.append('  );\n')
new_lines.append('}\n\n')

new_lines.append('export async function exportMonthlyReportCSV(monthYear?: string): Promise<string> {\n')
new_lines.append('  const report = await getMonthlyReport(monthYear);\n')
new_lines.append('  const csvLines = [\n')
new_lines.append('    "Metric,Value",\n')
new_lines.append('    `Month,${report.month_name}`,\n')
new_lines.append('    `Total Sales Revenue (INR),${report.total_sales}`,\n')
new_lines.append('    `Total Transactions,${report.total_transactions}`,\n')
new_lines.append('    `Waste Prevented Value (INR),${report.waste_prevented_value}`,\n')
new_lines.append('    `Actual Waste Value (INR),${report.actual_waste_value}`,\n')
new_lines.append('    `Average Green Score,${report.avg_green_score}`,\n')
new_lines.append('    `Top Category,${report.top_category}`,\n')
new_lines.append('    `Top Selling Product,"${report.top_selling_product}"`\n')
new_lines.append('  ];\n')
new_lines.append('  return csvLines.join("\\n");\n')
new_lines.append('}\n')

with open('lib/api.ts', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)
